version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: mefinance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    networks:
      - mefinance-net

  app:
    image: mefinance:latest
    container_name: mefinance_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mefinance
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      CORS_ORIGINS: http://localhost:4200
    ports:
      - "8080:8080"
    networks:
      - mefinance-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mefinance.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - mefinance-net

networks:
  mefinance-net: